"""Initial migration.

Revision ID: baeae2c5db20
Revises: 
Create Date: 2024-08-20 21:04:27.504644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeae2c5db20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_s', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_m', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_l', sa.Float(), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('dessert', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dessert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('price_l')
        batch_op.drop_column('price_m')
        batch_op.drop_column('price_s')

    # ### end Alembic commands ###
